# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Havit_Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Havit_Practice
	pod 'SnapKit', '~> 5.0.0'
	pod 'Then'
	pod 'RxSwift', '6.2.0'
    	pod 'RxCocoa', '6.2.0'

end
